# Generated by Django 5.1.3 on 2024-11-28 00:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Generos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genero', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_usuario', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('senha', models.CharField(max_length=200)),
                ('matricula', models.IntegerField(unique=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Livros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('autor', models.CharField(max_length=200, null=True)),
                ('is_rented', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, upload_to='image/')),
                ('genero_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='livros_genero_1', to='multimeios.generos')),
                ('genero_2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='livros_genero_2', to='multimeios.generos')),
            ],
        ),
    ]
